import React, { useState } from 'react';
import Head from 'next/head';
import FormRegister from '@/components/molecules/Form/FormRegister';
import FormLogin from '@/components/molecules/Form/FormLogin';

export default function AuthenticationPage() {
  const [toggle, setToggle] = useState(false);

  return (
    <>
      <div className='flex justify-center items-center w-full h-screen px-40 py-20 gap-x-10 bg-[url("/assets/images/waldemar-KoLjtiTAdgw-unsplash.jpg")] bg-cover'>
        <div className='flex justify-center items-center w-full h-full rounded-lg bg-white/20 shadow-lg backdrop-blur-lg'>
          {toggle ? (
            <>
              <Head>
                <title>PickmeLaundry - Register</title>
                <meta
                  name='description'
                  content='Generated by create next app'
                />
                <meta
                  name='viewport'
                  content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
              </Head>

              <div
                className={`flex flex-1 ${
                  toggle
                    ? 'absolute top-0 right-0 -translate-x-full w-[50%] overflow-hidden transition transform ease-in-out duration-1000 z-0'
                    : ''
                } flex-col justify-center items-center h-full rounded-l-lg z-0 py-4 gap-y-4`}
              >
                <div className='flex justify-center items-center w-full'>
                  <h1 className='text-5xl font-bold tracking-widest uppercase text-white'>
                    Register
                  </h1>
                </div>
                <div className='flex justify-center items-center w-full px-12 py-8 overflow-y-auto'>
                  <FormRegister />
                </div>
                <div className='flex justify-center items-center w-full gap-1'>
                  <h1 className='text-sm font-medium tracking-tight text-blue-950'>
                    Already have account?
                  </h1>
                  <button
                    onClick={() => {
                      setToggle(false);
                    }}
                    className='text-sm font-bold tracking-wider text-white hover:underline'
                  >
                    Login here
                  </button>
                </div>
              </div>
              <div
                className={`flex flex-1 ${
                  toggle
                    ? 'absolute top-0 left-0 translate-x-full w-[50%] overflow-hidden transition transform ease-in-out duration-1000 z-0'
                    : ''
                } justify-center items-center rounded-lg bg-[url("/assets/images/jean-philippe-delberghe-75xPHEQBmvA-unsplash.jpg")] bg-cover h-full p-10`}
              >
                <div className='flex flex-col justify-center items-center w-full'>
                  <div className='flex justify-center items-center w-full py-20 px-10 bg-blue-300/30 rounded-lg'>
                    <h1 className='text-blue-950 font-bold text-5xl'>
                      Please Register to Login
                    </h1>
                  </div>

                  <div className='flex justify-center items-center w-full pt-52'>
                    <h1 className='text-blue-950 font-thin text-sm'>
                      © Pickme Laundry 2023.
                    </h1>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <>
              <Head>
                <title>PickmeLaundry - Login</title>
                <meta
                  name='description'
                  content='Generated by create next app'
                />
                <meta
                  name='viewport'
                  content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
              </Head>

              <div
                className={`flex flex-1 ${
                  !toggle
                    ? 'absolute top-0 right-0 translate-x-0 w-[50%] overflow-hidden transition transform ease-in-out duration-1000 z-0'
                    : ''
                } flex-col justify-center items-center h-full rounded-r-lg z-0`}
              >
                <div className='flex justify-center items-center w-full'>
                  <h1 className='text-5xl font-bold tracking-widest uppercase text-white'>
                    Login
                  </h1>
                </div>
                <div className='flex justify-center items-center w-full px-12 py-8'>
                  <FormLogin />
                </div>
                <div className='flex justify-center items-center w-full gap-1'>
                  <h1 className='text-sm font-medium tracking-tight text-blue-950'>
                    Don't have account?
                  </h1>
                  <button
                    onClick={() => {
                      setToggle(true);
                    }}
                    className='text-sm font-bold tracking-wider text-white hover:underline'
                  >
                    Register here
                  </button>
                </div>
              </div>
              <div
                className={`flex flex-1 ${
                  !toggle
                    ? 'absolute top-0 left-0 translate-x-0 w-[50%] overflow-hidden transition transform ease-in-out duration-1000 z-0'
                    : ''
                } justify-center items-center rounded-l-lg bg-[url("/assets/images/jean-philippe-delberghe-75xPHEQBmvA-unsplash.jpg")] bg-cover h-full p-10`}
              >
                <div className='flex flex-col justify-center items-center w-full'>
                  <div className='flex justify-center items-center w-full py-20 px-10 bg-blue-300/30 rounded-lg'>
                    <h1 className='text-blue-950 font-bold text-5xl'>
                      Hi! Please Login to Continue
                    </h1>
                  </div>

                  <div className='flex justify-center items-center w-full pt-52'>
                    <h1 className='text-blue-950 font-thin text-sm'>
                      © Pickme Laundry 2023.
                    </h1>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </>
  );
}
