import React, { useState } from 'react';
import Image from 'next/image';
import Head from 'next/head';
import Field from '@/components/atoms/Heading/Field';
import Label from '@/components/atoms/Label';
import Input from '@/components/atoms/Input';
import Button from '@/components/atoms/Button';
import Icons from '@/components/atoms/Icons';
import MainLayout from '@/components/templates/Main';

export default function Profile() {
  const [imageSrc, setImageSrc] = useState(
    '/assets/images/alex-suprun-ZHvM3XIOHoE-unsplash.jpg'
  );

  const handleImageChange = (event) => {
    const file = event.target.files[0];
    const reader = new FileReader();

    reader.onloadend = () => {
      setImageSrc(reader.result);
    };

    if (file) {
      reader.readAsDataURL(file);
    }
  };

  return (
    <>
      <Head>
        <title>PickmeLaundry - Profile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainLayout>
        <div className='flex justify-center items-center w-full p-10'>
          <div className='flex flex-1 flex-col justify-center items-center gap-y-8 p-8'>
            <div className='flex justify-end items-center w-full'>
              <div className='flex justify-center items-center absolute -translate-x-36 translate-y-10'>
                <label
                  htmlFor='form-upload'
                  className='cursor-pointer hover:scale-110 transition duration-200'
                >
                  <Icons.Pen />
                </label>

                <input
                  id='form-upload'
                  type='file'
                  accept='image/*'
                  onChange={handleImageChange}
                  className='hidden'
                />
              </div>
            </div>
            <div className='flex justify-center items-center w-full'>
              <Image
                src={imageSrc}
                alt='image'
                width='300'
                height='300'
                className='rounded-full'
              />
            </div>
            <div className='flex justify-center items-center w-full pl-44'>
              <div className='flex flex-col justify-center items-center w-full'>
                <Field keys='Name' fill='John Doe' />
                <Field keys='Email' fill='john@gmail.com' />
                <Field keys='Phone Number' fill='0895-1234-5678' />
                <Field keys='Address' fill='Perumahan Graha Permai no.1' />
              </div>
            </div>
          </div>
          <div className='flex flex-col flex-1 justify-center items-center gap-y-8 p-8 '>
            <div className='flex justify-center items-center w-full'>
              <h1 className='text-3xl font-bold text-blue-950'>
                Edit Your Profile
              </h1>
            </div>
            <form className='flex flex-col justify-center items-center w-full gap-y-4'>
              <div className='flex flex-col w-full gap-y-1'>
                <Label>Name</Label>
                <Input />
              </div>

              <div className='flex flex-col w-full gap-y-1'>
                <Label>Email</Label>
                <Input />
              </div>

              <div className='flex flex-col w-full gap-y-1'>
                <Label>Phone Number</Label>
                <Input />
              </div>

              <div className='flex flex-col w-full gap-y-1'>
                <Label>Address</Label>
                <textarea className='px-4 py-2 text-sm w-full border rounded outline-none focus:ring focus:ring-blue-900 transition duration-300 bg-gray-100 resize-none h-32'></textarea>
              </div>

              <div className='flex flex-col w-full py-4'>
                <Button>Edit Profile</Button>
              </div>
            </form>
          </div>
        </div>
        {/* <div className='bg-white p-8'>
        <h1 className='font-bold text-2xl mb-6'>Profil Pelanggan</h1>
        <div className='flex items-center'>
          <img
            className='w-[200px] h-[150px] mr-8'
            src='/assets/images/alex-suprun-ZHvM3XIOHoE-unsplash.jpg'
            alt='images'
          />
          <div>
            <div className='mb-4 font-semibold'>
              <p className='mb-2'>Nama: Natasya Lydia</p>
              <p className='mb-2'>Alamat: Tanggerang Selatan</p>
            </div>
            <div className='flex flex-col mb-4 font-semibold'>
              <p className='mb-2'>Email: Natasya@gmail.com</p>
              <p className='mb-2'>Nomor Telepon: 081234567892</p>
            </div>
          </div>
        </div>
        <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded absolute top-0 right-0 mt-6 mr-6'>
          Edit Profile
        </button>
      </div> */}
      </MainLayout>
    </>
  );
}
