import React, { useState } from 'react';
import Head from 'next/head';
import SecondLayout from '@/components/templates/Second';
import Modal from '@/components/atoms/Modal';
import Label from '@/components/atoms/Label';
import Input from '@/components/atoms/Input';
import Button from '@/components/atoms/Button';

export default function Users() {
  const [confirm, setConfirm] = useState(false);
  return (
    <>
      <Head>
        <title>Pickme - Admin Order List</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {confirm && (
        <Modal
          type='admin'
          state={confirm}
          setState={setConfirm}
          title='Confirm Order'
        >
          <form className='flex flex-col justify-center items-center w-full p-8 gap-y-4'>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Weight</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Processing Time</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Total Price</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Button>Submit</Button>
            </div>
          </form>
        </Modal>
      )}

      <SecondLayout title='Order List'>
        <div className='flex justify-center items-center w-full relative overflow-x-auto shadow-md sm:rounded-lg'>
          <table className='w-full text-sm text-left text-gray-500 dark:text-gray-400'>
            <thead className='text-gray-700 bg-blue-200 dark:bg-gray-700 dark:text-gray-400'>
              <tr>
                <th scope='col' className='px-6 py-3'>
                  No.
                </th>
                <th scope='col' className='px-6 py-3'>
                  Name
                </th>
                <th scope='col' className='px-6 py-3'>
                  Date Order
                </th>
                <th scope='col' className='px-6 py-3'>
                  Service Types
                </th>
                <th scope='col' className='px-6 py-3'>
                  Status
                </th>
                <th scope='col' className='px-6 py-3'>
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  1
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>04/07/2023</td>
                <td className='px-6 py-4'>Iron Only</td>
                <td className='px-6 py-4'>Waiting to Confirm</td>
                <td className='px-6 py-4 space-x-2'>
                  <button
                    onClick={() => setConfirm(true)}
                    className='font-medium text-blue-600 dark:text-blue-500 hover:underline'
                  >
                    Confirm
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  2
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>04/07/2023</td>
                <td className='px-6 py-4'>Iron Only</td>
                <td className='px-6 py-4'>Waiting to Confirm</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Confirm
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  3
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>04/07/2023</td>
                <td className='px-6 py-4'>Iron Only</td>
                <td className='px-6 py-4'>Waiting to Confirm</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Confirm
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  4
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>04/07/2023</td>
                <td className='px-6 py-4'>Iron Only</td>
                <td className='px-6 py-4'>Waiting to Confirm</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Confirm
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  5
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>04/07/2023</td>
                <td className='px-6 py-4'>Iron Only</td>
                <td className='px-6 py-4'>Waiting to Confirm</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Confirm
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </SecondLayout>
    </>
  );
}
