import React, { useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import MainLayout from '@/components/templates/Main';
import Label from '@/components/atoms/Label';
import Input from '@/components/atoms/Input';
import Button from '@/components/atoms/Button';
import Icons from '@/components/atoms/Icons';
import Carousel from '@/components/organisms/Carousel';
import Field from '@/components/atoms/Heading/Field';
import Modal from '@/components/atoms/Modal';

export default function Home() {
  const [order, setOrder] = useState(false);
  const [realTime, setRealTime] = useState(false);
  const [history, setHistory] = useState(false);
  const [detail, setDetail] = useState(null);

  const router = useRouter();
  const images = [
    '/assets/images/image-carousel-1.png',
    '/assets/images/image-carousel-2.png',
    '/assets/images/image-carousel-3.png',
  ];

  return (
    <>
      <Head>
        <title>PickmeLaundry - Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {order && (
        <Modal state={order} setState={setOrder} title='Order Detail'>
          <div className='flex flex-col flex-1 justify-start items-start w-full'>
            <Field keys='Name' fill='John Doe' />
            <Field keys='Pick-up Date' fill='04/07/2023' />
            <Field keys='Service Types' fill='Iron Only' />
            <Field keys='Laundry Weight' fill='3 Kilograms' />
            <Field keys='Status' fill='On Progress' />
            <Field keys='Order Date' fill='04/07/2023' />
            <Field keys='Completion Type' fill='2 Days' />
            <Field keys='Remaining Time' fill='1 Days' />

            <div className='absolute bottom-8 flex flex-col'>
              <h1 className='text-xl font-bold text-blue-950'>Total Price</h1>
              <h1 className='text-xl font-bold text-blue-900'>Rp50.000</h1>
            </div>
          </div>
          <div className='flex flex-col flex-1 justify-start items-start w-full gap-y-2'>
            <h1 className='text-md font-medium text-blue-950'>Track Pick-up</h1>
            <iframe
              src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63463.90567978818!2d106.6827849486328!3d-6.198354199999984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e788286b43b10cd%3A0x94d120227ac1d0f!2sNasi%20Cumi%20Hitam%20Pak%20Kris!5e0!3m2!1sid!2sid!4v1688466981856!5m2!1sid!2sid'
              width='600'
              height='450'
              loading='lazy'
              referrerPolicy='no-referrer-when-downgrade'
              className='rounded-lg drop-shadow-md'
            ></iframe>
          </div>
        </Modal>
      )}

      {realTime && (
        <Modal
          state={realTime}
          setState={setRealTime}
          title='Real-Time Laundry'
        >
          <div className='flex flex-col justify-center items-start w-full gap-y-10'>
            <div className='flex flex-col justify-start items-start w-1/2'>
              <Field keys='Name' fill='John Doe' />
              <Field keys='Pick-up Date' fill='04/07/2023' />
              <Field keys='Service Types' fill='Iron Only' />
              <Field keys='Laundry Weight' fill='3 Kilograms' />
              <Field keys='Status' fill='On Progress' />
              <Field keys='Order Date' fill='04/07/2023' />
            </div>
            <div className='flex flex-col justify-start items-start w-full pb-8'>
              <ol class='flex items-center w-full'>
                <li class="flex w-full items-center text-blue-600 dark:text-blue-500 after:content-[''] after:w-full after:h-1 after:border-b after:border-blue-900 after:border-4 after:inline-block dark:after:border-blue-800">
                  <span class='flex items-center justify-center w-10 h-10 bg-blue-900 rounded-full lg:h-12 lg:w-12 dark:bg-blue-800 shrink-0'>
                    <Icons.Check />
                  </span>
                  <div className='absolute bottom-10'>
                    <h1 className='text-sm font-medium text-blue-950 translate-x-1'>
                      Order
                    </h1>
                  </div>
                </li>
                <li class="flex w-full items-center after:content-[''] after:w-full after:h-1 after:border-b after:border-gray-100 after:border-4 after:inline-block dark:after:border-gray-700">
                  <span class='flex items-center justify-center w-10 h-10 bg-gray-100 rounded-full lg:h-12 lg:w-12 dark:bg-gray-700 shrink-0'>
                    <Icons.DoubleCheck />
                  </span>
                  <div className='absolute bottom-10 '>
                    <h1 className='text-sm font-medium text-blue-950 -translate-x-5'>
                      Confirm Order
                    </h1>
                  </div>
                </li>
                <li class="flex w-full items-center after:content-[''] after:w-full after:h-1 after:border-b after:border-gray-100 after:border-4 after:inline-block dark:after:border-gray-700">
                  <span class='flex items-center justify-center w-10 h-10 bg-gray-100 rounded-full lg:h-12 lg:w-12 dark:bg-gray-700 shrink-0'>
                    <Icons.Clock />
                  </span>
                  <div className='absolute bottom-10 '>
                    <h1 className='text-sm font-medium text-blue-950'>
                      Progress
                    </h1>
                  </div>
                </li>
                <li class="flex w-full items-center after:content-[''] after:w-full after:h-1 after:border-b after:border-gray-100 after:border-4 after:inline-block dark:after:border-gray-700">
                  <span class='flex items-center justify-center w-10 h-10 bg-gray-100 rounded-full lg:h-12 lg:w-12 dark:bg-gray-700 shrink-0'>
                    <Icons.Truck />
                  </span>
                  <div className='absolute bottom-10 '>
                    <h1 className='text-sm font-medium text-blue-950'>
                      Delivery
                    </h1>
                  </div>
                </li>
                <li class='flex items-center w-full'>
                  <span class='flex items-center justify-center w-10 h-10 bg-gray-100 rounded-full lg:h-12 lg:w-12 dark:bg-gray-700 shrink-0'>
                    <Icons.Coin />
                  </span>
                  <div className='absolute bottom-10 '>
                    <h1 className='text-sm font-medium text-blue-950'>
                      Payment
                    </h1>
                  </div>
                </li>
              </ol>
            </div>
          </div>
        </Modal>
      )}

      {history && (
        <Modal state={history} setState={setHistory} title='Order History'>
          <div className='flex flex-col justify-center items-center w-full max-h-full py-8 gap-y-8 overflow-y-auto'>
            <div className='flex justify-between items-center w-full bg-blue-100 drop-shadow-md rounded-lg py-4 px-8'>
              <div className='flex justify-start items-center gap-x-4 '>
                <div className='flex justify-center items-center p-2 rounded-full bg-blue-900'>
                  <Icons.History />
                </div>

                <div className='flex flex-col justify-center items-start'>
                  <h1 className='text-xl font-bold text-blue-950'>Wash Only</h1>
                  <h1 className='text-sm font-medium text-blue-950'>
                    04/07/2023
                  </h1>
                  <h1 className='text-sm font-medium text-blue-950'>
                    Rp50.000
                  </h1>
                </div>
              </div>

              <div className='flex justify-center items-center'>
                <button
                  onClick={() => {
                    setDetail(detail ? null : 'detail-1');
                  }}
                  className='text-lg font-bold text-blue-900'
                >
                  More Detail
                </button>
              </div>
            </div>
            {detail === 'detail-1' && (
              <div className='flex justify-center items-center w-full bg-white drop-shadow-md rounded-lg p-5'>
                <div className='flex flex-col flex-1 justify-start items-center'>
                  <Field keys='Name' fill='John Doe' />
                  <Field keys='Pick-up Date' fill='04/07/2023' />
                  <Field keys='Service Types' fill='Iron Only' />
                </div>
                <div className='flex flex-col  flex-1 justify-start items-center'>
                  <Field keys='Laundry Weight' fill='3 Kilograms' />
                  <Field keys='Status' fill='On Progress' />
                  <Field keys='Order Date' fill='04/07/2023' />
                </div>
              </div>
            )}

            <div className='flex justify-between items-center w-full bg-blue-100 drop-shadow-md rounded-lg py-4 px-8'>
              <div className='flex justify-start items-center gap-x-4 '>
                <div className='flex justify-center items-center p-2 rounded-full bg-blue-900'>
                  <Icons.History />
                </div>

                <div className='flex flex-col justify-center items-start'>
                  <h1 className='text-xl font-bold text-blue-950'>Wash Only</h1>
                  <h1 className='text-sm font-medium text-blue-950'>
                    04/07/2023
                  </h1>
                  <h1 className='text-sm font-medium text-blue-950'>
                    Rp50.000
                  </h1>
                </div>
              </div>

              <div className='flex justify-center items-center'>
                <button
                  onClick={() => setDetail(detail ? null : 'detail-2')}
                  className='text-lg font-bold text-blue-900'
                >
                  More Detail
                </button>
              </div>
            </div>
            {detail === 'detail-2' && (
              <div className='flex justify-center items-center w-full bg-white drop-shadow-md rounded-lg p-5'>
                <div className='flex flex-col flex-1 justify-start items-center'>
                  <Field keys='Name' fill='John Doe' />
                  <Field keys='Pick-up Date' fill='04/07/2023' />
                  <Field keys='Service Types' fill='Iron Only' />
                </div>
                <div className='flex flex-col  flex-1 justify-start items-center'>
                  <Field keys='Laundry Weight' fill='3 Kilograms' />
                  <Field keys='Status' fill='On Progress' />
                  <Field keys='Order Date' fill='04/07/2023' />
                </div>
              </div>
            )}
          </div>
        </Modal>
      )}

      <MainLayout>
        <div className='flex justify-center items-center w-full'>
          <div className='flex justify-center items-center w-full'>
            <Carousel images={images} />
          </div>

          <div className='flex flex-wrap justify-center items-center w-1/3 rounded-lg drop-shadow-md bg-white absolute -bottom-12 p-10 z-0'>
            <div className='flex justify-center items-center gap-x-12'>
              <button
                onClick={() => setOrder(true)}
                className='flex flex-col justify-center items-center gap-y-4'
              >
                <div className='flex justify-center items-center rounded-full bg-blue-900 w-16 h-16 hover:translate-y-2 transition duration-300'>
                  <Icons.Bill />
                </div>
                <h1 className='font-medium text-md text-blue-950'>
                  Order Detail
                </h1>
              </button>

              <button
                onClick={() => setRealTime(true)}
                className='flex flex-col justify-center items-center gap-y-4'
              >
                <div className='flex justify-center items-center rounded-full bg-blue-900 w-16 h-16 hover:translate-y-2 transition duration-300'>
                  <Icons.Resume />
                </div>

                <h1 className='font-medium text-md text-blue-950'>
                  Realtime Progress
                </h1>
              </button>

              <button
                onClick={() => setHistory(true)}
                className='flex flex-col justify-center items-center gap-y-4'
              >
                <div className='flex justify-center items-center rounded-full bg-blue-900 w-16 h-16 hover:translate-y-2 transition duration-300'>
                  <Icons.History />
                </div>

                <h1 className='font-medium text-md text-blue-950'>
                  Order History
                </h1>
              </button>
            </div>
          </div>
        </div>

        {/* service types */}
        <div className='flex flex-col justify-center items-center w-full h-screen'>
          <div className='flex flex-col justify-center items-center mb-8'>
            <h1 className='text-4xl font-bold text-blue-900 uppercase'>
              service types
            </h1>
            <span className='w-1/2 border border-blue-950/20 mt-8'></span>
          </div>

          <div className='flex flex-wrap justify-center items-center w-full gap-x-8'>
            {/* service card */}
            <div className='flex flex-col border-2 border-blue-900 rounded-lg px-20 py-10 shadow-lg w-80 h-60 hover:shadow-2xl transition duration-150'>
              <h1 className='text-2xl font-bold text-blue-950'>Full service</h1>

              <ul className='text-md text-blue-950 list-disc'>
                <li>Washing</li>
                <li>Ironing</li>
                <li>Clothes pick-up</li>
                <li>Max 48 hours service</li>
              </ul>
            </div>

            <div className='flex flex-col border-2 border-blue-900 rounded-lg px-20 py-10 shadow-lg w-80 h-60 hover:shadow-2xl transition duration-150'>
              <h1 className='text-2xl font-bold text-blue-950'>Wash Only</h1>

              <ul className='text-md text-blue-950 list-disc'>
                <li>Washing</li>
                <li>Clothes pick-up</li>
                <li>Max 48 hours service</li>
              </ul>
            </div>

            <div className='flex flex-col border-2 border-blue-900 rounded-lg px-20 py-10 shadow-lg w-80 h-60 hover:shadow-2xl transition duration-150'>
              <h1 className='text-2xl font-bold text-blue-950'>Iron Only</h1>

              <ul className='text-md text-blue-950 list-disc'>
                <li>Ironing</li>
                <li>Clothes pick-up</li>
                <li>Max 48 hours service</li>
              </ul>
            </div>

            <div className='flex flex-col border-2 border-blue-900 rounded-lg px-20 py-10 shadow-lg w-80 h-60 hover:shadow-2xl transition duration-150'>
              <h1 className='text-2xl font-bold text-blue-950'>Dry Clean</h1>

              <ul className='text-md text-blue-950 list-disc'>
                <li>Dry Cleaning</li>
                <li>Clothes pick-up</li>
                <li>Max 48 hours service</li>
              </ul>
            </div>
          </div>
        </div>

        {/* pickup request */}
        <div className='flex flex-col justify-center items-center w-full h-screen bg-[url("/assets/images/arron-choi-kRK1Bne4xEw-unsplash.jpg")] bg-cover'>
          <div className='flex justify-center items-center w-full h-full bg-black/50 p-10'>
            <div className='flex flex-1 flex-col justify-center items-center'>
              <div className='flex flex-col justify-start items-start px-1'>
                <h1 className='text-5xl font-bold text-white'>
                  Pick Me Laundry
                </h1>
                <span className='w-1/2 border-2 border-white my-2'></span>
                <p className='text-lg font-thin text-white'>
                  The best platform to solve your dirty laundry problem
                </p>
              </div>
            </div>
            <div className='flex flex-1 flex-col justify-center items-center'>
              <div className='flex flex-col justify-center items-center w-4/5 bg-white rounded-lg px-5 py-10 gap-y-5'>
                <div className='flex flex-col justify-center items-center w-full '>
                  <h1 className='text-3xl font-bold text-blue-900 uppercase'>
                    Pick-up Request
                  </h1>
                  <p className='text-sm font-medium text-blue-950'>
                    Please complete the form below to use our service
                  </p>
                </div>
                <form className='flex flex-col justify-start items-center w-full px-8 gap-y-4'>
                  {/* <div className='flex flex-col w-full gap-y-1'>
                  <Label>Name</Label>
                  <Input />
                </div>

                <div className='flex flex-col w-full gap-y-1'>
                  <Label>Phone Number</Label>
                  <Input />
                </div> */}

                  <div className='flex flex-col w-full gap-y-1'>
                    <Label>Pick-up Date</Label>
                    <Input />
                  </div>

                  <div className='flex flex-col w-full gap-y-1'>
                    <Label>Service Types</Label>
                    <select
                      name='serviceTypes'
                      id='serviceTypes'
                      className='px-4 py-2 w-full text-sm border rounded outline-none focus:ring focus:ring-blue-900 transition duration-300 bg-gray-100'
                    >
                      <option defaultValue='select' disabled>
                        Select Service Type
                      </option>
                      <option value='fullService'>Full Service</option>
                      <option value='washOnly'>Wash Only</option>
                      <option value='ironOnly'>Iron Only</option>
                      <option value='dryClean'>Dry Cleaning</option>
                    </select>
                  </div>

                  <div className='flex flex-col w-full gap-y-1'>
                    <Label>
                      Laundry Weight
                      <p className='text-xs font-normal'>*optional</p>
                    </Label>
                    <Input />
                  </div>

                  {/* <div className='flex flex-col w-full gap-y-1'>
                  <Label>Address</Label>
                  <textarea
                    name='address'
                    id='address'
                    className='px-4 py-2 w-full text-sm border rounded outline-none focus:ring focus:ring-blue-900 transition duration-300 bg-gray-100 resize-none h-16'
                  ></textarea>
                </div> */}

                  <div className='flex flex-col w-full gap-y-1'>
                    <Button>Submit</Button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </MainLayout>
    </>
  );
}
