import Head from 'next/head';
import Header from '@/components/organisms/Section/SectionHeader';
import About from '@/components/organisms/Section/SectionAbout';
import Service from '@/components/organisms/Section/SectionService';
import Contact from '@/components/organisms/Section/SectionContact';
import Footer from '@/components/organisms/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pickme - Laundry</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* ========== Header ========== Section ========== */}
      <Header />

      {/* ========== About ========== Section ========== */}
      <About />

      {/* ========== Service ========== Section ========== */}
      <Service />

      {/* ========== Contact ========== Section ========== */}
      <Contact />

      {/* ==========  Footer  ========== */}
      <Footer />
    </>
  );
}
