import React, { useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import SecondLayout from '@/components/templates/Second';
import Modal from '@/components/atoms/Modal';
import Label from '@/components/atoms/Label';
import Input from '@/components/atoms/Input';
import Button from '@/components/atoms/Button';

export default function Users() {
  const [edit, setEdit] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(false);

  return (
    <>
      <Head>
        <title>Pickme - Admin User List</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {edit && (
        <Modal type='admin' state={edit} setState={setEdit} title='Edit User'>
          <form className='flex flex-col justify-center items-center w-full p-8 gap-y-4'>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Name</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Email</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Phone Number</Label>
              <Input />
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Label>Address</Label>
              <textarea
                name='address'
                id='address'
                className=' px-4 py-2 w-full border rounded outline-none focus:ring focus:ring-blue-900 transition duration-300 bg-gray-100 resize-none h-24'
              ></textarea>
            </div>
            <div className='flex flex-col w-full gap-y-1'>
              <Button
                onClick={(e) => {
                  e.preventDefault();
                  setEdit(false);
                  setTimeout(() => {
                    toast.success('Success to edit User', {
                      position: toast.POSITION.TOP_RIGHT,
                    });
                  }, 500);
                }}
              >
                Submit
              </Button>
            </div>
          </form>
        </Modal>
      )}

      {deleteConfirm && (
        <Modal
          type='admin'
          state={deleteConfirm}
          setState={setDeleteConfirm}
          title='Delete User'
          textColor='text-red-500'
        >
          <div className='flex flex-col justify-center items-center w-full p-4 gap-y-8'>
            <div className='flex justify-center items-center w-full px-20'>
              <h1 className='text-3xl font-medium '>
                Do you sure want to delete this user?
              </h1>
            </div>
            <div className='flex justify-center items-center w-full px-24 gap-x-12'>
              <Button>No</Button>
              <Button color='bg-red-500' hover='hover:bg-red-700'>
                Yes
              </Button>
            </div>
          </div>
        </Modal>
      )}

      {/* notify */}
      <ToastContainer />

      <SecondLayout title='User List'>
        <div className='flex justify-center items-center w-full relative overflow-x-auto shadow-md sm:rounded-lg'>
          <table className='w-full text-sm text-left text-gray-500 dark:text-gray-400'>
            <thead className=' text-gray-700 bg-blue-200 dark:bg-gray-700 dark:text-gray-400'>
              <tr>
                <th scope='col' className='px-6 py-3'>
                  No.
                </th>
                <th scope='col' className='px-6 py-3'>
                  Name
                </th>
                <th scope='col' className='px-6 py-3'>
                  Email
                </th>
                <th scope='col' className='px-6 py-3'>
                  Phone Number
                </th>
                <th scope='col' className='px-6 py-3'>
                  Address
                </th>
                <th scope='col' className='px-6 py-3'>
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  1
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>john@gmail.com</td>
                <td className='px-6 py-4'>0891-2345-6789</td>
                <td className='px-6 py-4'>Perumahan Graha Permai no.1</td>
                <td className='px-6 py-4 space-x-2'>
                  <button
                    onClick={() => setEdit(true)}
                    className='font-medium text-blue-600 dark:text-blue-500 hover:underline'
                  >
                    Edit
                  </button>
                  <button
                    onClick={() => setDeleteConfirm(true)}
                    className='font-medium text-red-600 dark:text-blue-500 hover:underline'
                  >
                    Delete
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  2
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>john@gmail.com</td>
                <td className='px-6 py-4'>0891-2345-6789</td>
                <td className='px-6 py-4'>Perumahan Graha Permai no.1</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Edit
                  </button>
                  <button className='font-medium text-red-600 dark:text-blue-500 hover:underline'>
                    Delete
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  3
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>john@gmail.com</td>
                <td className='px-6 py-4'>0891-2345-6789</td>
                <td className='px-6 py-4'>Perumahan Graha Permai no.1</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Edit
                  </button>
                  <button className='font-medium text-red-600 dark:text-blue-500 hover:underline'>
                    Delete
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  4
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>john@gmail.com</td>
                <td className='px-6 py-4'>0891-2345-6789</td>
                <td className='px-6 py-4'>Perumahan Graha Permai no.1</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Edit
                  </button>
                  <button className='font-medium text-red-600 dark:text-blue-500 hover:underline'>
                    Delete
                  </button>
                </td>
              </tr>
              <tr className='bg-white border-b dark:bg-gray-800 dark:border-gray-700'>
                <th
                  scope='row'
                  className='px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white'
                >
                  5
                </th>
                <td className='px-6 py-4'>John Doe</td>
                <td className='px-6 py-4'>john@gmail.com</td>
                <td className='px-6 py-4'>0891-2345-6789</td>
                <td className='px-6 py-4'>Perumahan Graha Permai no.1</td>
                <td className='px-6 py-4 space-x-2'>
                  <button className='font-medium text-blue-600 dark:text-blue-500 hover:underline'>
                    Edit
                  </button>
                  <button className='font-medium text-red-600 dark:text-blue-500 hover:underline'>
                    Delete
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </SecondLayout>
    </>
  );
}
